version: '3.8'

services:
  backend:
    build:
      context: ./web_urban_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:./data/demo-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    command: mvn spring-boot:run 


  frontend:
    build:
      context: ./web_urban_front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend