package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.Table;
import java.sql.Date;

/**
 * Represents a Motorman entity in the system.
 *
 * <p>A Motorman is associated with an Employee and has a permit number,
 * a permit expiry date, and a medical check expiry date.
 * </p>
 */
@Entity
@Table(name = "MOTORMEN")
public class Motorman {

  /**
   * Unique identifier for the Motorman.
   * Auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The employee associated with this Motorman.
   * Maps to the EMPLOYEE_ID column in the MOTORMEN table.
   */
  @ManyToOne
  @MapsId
  @JoinColumn(name = "EMPLOYEE_ID")
  private Employee employee;

  /**
   * The official permit number assigned to the Motorman.
   * Cannot be null.
   */
  @Column(nullable = false)
  private String permitNumber;

  /**
   * The expiry date of the Motorman's permit.
   * Cannot be null.
   */
  @Column(nullable = false)
  private Date permitExpiryDate;

  /**
   * The expiry date of the Motorman's medical check certificate.
   * Cannot be null.
   */
  @Column(nullable = false)
  private Date medicalCheckExpiryDate;
}
