package com.example.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a Point of Sale (POS) in the system.
 *
 * <p>A Point of Sale is associated with a specific {@link Address} and
 * {@link Office}.
 * </p>
 */
@Entity
@Table(name = "POINTS_OF_SALE")
public class PointOfSale {

  /**
   * The unique identifier of the Point of Sale.
   * This value is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The address associated with this Point of Sale.
   * Cannot be null.
   */
  @ManyToOne
  @JoinColumn(name = "ADDRESS_ID", nullable = false,
      foreignKey = @ForeignKey(name = "FK_POINT_OF_SALE_ADDRESS"))
  private Address address;

  /**
   * The office associated with this Point of Sale.
   * Cannot be null.
   */
  @ManyToOne
  @JoinColumn(name = "OFFICE_ID", nullable = false,
      foreignKey = @ForeignKey(name = "FK_POINT_OF_SALE_OFFICE"))
  private Office office;

  /**
   * Gets the unique identifier of this Point of Sale.
   *
   * @return the id
   */
  public int getId() {
    return id;
  }

  /**
   * Sets the unique identifier of this Point of Sale.
   *
   * @param idParam the id to set
   */
  public void setId(final int idParam) {
    this.id = idParam;
  }

  /**
   * Gets the address associated with this Point of Sale.
   *
   * @return the address
   */
  public Address getAddress() {
    return address;
  }

  /**
   * Sets the address for this Point of Sale.
   *
   * @param addressParam the address to set
   */
  public void setAddress(final Address addressParam) {
    this.address = addressParam;
  }

  /**
   * Gets the office associated with this Point of Sale.
   *
   * @return the office
   */
  public Office getOffice() {
    return office;
  }

  /**
   * Sets the office for this Point of Sale.
   *
   * @param officeParam the office to set
   */
  public void setOffice(final Office officeParam) {
    this.office = officeParam;
  }
}
