package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entity representing a Position within the organization.
 *
 * <p>This class maps to the {@code POSITIONS} table in the database and
 * contains
 * the unique identifier and name of the position.
 * </p>
 */
@Entity
@Table(name = "POSITIONS")
public class Position {

  /**
   * The unique identifier of the position.
   *
   * <p>This field is automatically generated by the database.
   * </p>
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The name of the position.
   *
   * <p>Cannot be {@code null}.
   * </p>
   */
  @Column(nullable = false)
  private String positionName;

  /**
   * Returns the unique identifier of this position.
   *
   * @return the position ID
   */
  public int getId() {
    return id;
  }

  /**
   * Sets the unique identifier of this position.
   *
   * @param idParam the position ID to set
   */
  public void setId(final int idParam) {
    this.id = idParam;
  }

  /**
   * Returns the name of this position.
   *
   * @return the position name
   */
  public String getPositionName() {
    return positionName;
  }

  /**
   * Sets the name of this position.
   *
   * @param positionNameParam the position name to set; must not be {@code null}
   */
  public void setPositionName(final String positionNameParam) {
    this.positionName = positionNameParam;
  }
}
