package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a salary entity mapped to the {@code Salaries} table in the
 * database.
 */
@Entity
@Table(name = "Salaries")
public class Salary {

  /**
   * The unique identifier for the salary record.
   *
   * <p>This value is automatically generated by the database.
   * </p>
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The monetary amount of the salary.
   *
   * <p>This field is required and cannot be {@code null}.
   * </p>
   */
  @Column(nullable = false)
  private int amount;

  /**
   * Retrieves the unique identifier of this salary.
   *
   * @return the salary ID
   */
  public int getId() {
    return id;
  }

  /**
   * Sets the unique identifier for this salary.
   *
   * <p>Normally, this should not be called manually since the ID
   * is managed by the persistence provider.
   * </p>
   *
   * @param idParam the salary ID to set
   */
  public void setId(final int idParam) {
    this.id = idParam;
  }

  /**
   * Retrieves the salary amount.
   *
   * @return the salary amount
   */
  public int getAmount() {
    return amount;
  }

  /**
   * Sets the salary amount.
   *
   * @param amountParam the salary amount to set
   */
  public void setAmount(final int amountParam) {
    this.amount = amountParam;
  }
}
