package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a Stop entity in the transportation system.
 * Each Stop has a unique identifier, a name, and is associated with an Address.
 */
@Entity
@Table(name = "STOPS")
public class Stop {

  /**
   * The unique identifier of the stop.
   * This value is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The name of the stop.
   * Cannot be null.
   */
  @Column(nullable = false)
  private String stopName;

  /**
   * The address associated with this stop.
   * Cannot be null. Enforced with a foreign key constraint.
   */
  @ManyToOne
  @JoinColumn(name = "ADDRESS_ID", nullable = false,
      foreignKey = @ForeignKey(name = "FK_STOP_ADDRESS"))
  private Address address;

  /**
   * Returns the unique identifier of this stop.
   *
   * @return the id of the stop
   */
  public int getId() {
    return id;
  }

  /**
   * Sets the unique identifier of this stop.
   * Typically used by the persistence framework and should not be modified
   * manually.
   *
   * @param stopIdParam the id to set
   */
  public void setId(final int stopIdParam) {
    this.id = stopIdParam;
  }

  /**
   * Returns the name of this stop.
   *
   * @return the stop name
   */
  public String getStopName() {
    return stopName;
  }

  /**
   * Sets the name of this stop.
   *
   * @param stopNameParam the stop name to set
   */
  public void setStopName(final String stopNameParam) {
    this.stopName = stopNameParam;
  }

  /**
   * Returns the address associated with this stop.
   *
   * @return the associated Address
   */
  public Address getAddress() {
    return address;
  }

  /**
   * Sets the address associated with this stop.
   *
   * @param addressParam the Address to associate with this stop
   */
  public void setAddress(final Address addressParam) {
    this.address = addressParam;
  }
}
