package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.sql.Date;

/**
 * Represents a sale of a ticket at a specific point of sale.
 *
 * <p>This entity links tickets to the points of sale where they were purchased,
 * including the date of purchase.
 * </p>
 */
@Entity
@Table(name = "TICKETS_SALE_POINTS")
public class TicketSalePoint {

  /**
   * Unique identifier for the TicketSalePoint.
   * This value is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The point of sale where the ticket was purchased.
   * This is a mandatory field referencing the {@link PointOfSale} entity.
   */
  @ManyToOne
  @JoinColumn(
      name = "POINT_OF_SALE_ID",
      nullable = false,
      foreignKey = @ForeignKey(name = "FK_TICKET_SALE_POINT_POINT_OF_SALE")
  )
  private PointOfSale pointOfSale;

  /**
   * The ticket that was sold.
   * This is a mandatory field referencing the {@link Ticket} entity.
   */
  @ManyToOne
  @JoinColumn(
      name = "TICKET_ID",
      nullable = false,
      foreignKey = @ForeignKey(name = "FK_TICKET_SALE_POINT_TICKET")
  )
  private Ticket ticket;

  /**
   * The date when the ticket was purchased.
   */
  @Column
  private Date purchaseDate;

}
