package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.sql.Date;

/**
 * Entity representing a ticket in the system.
 *
 * <p>Each ticket has a unique identifier, a duration, and a price.
 * </p>
 */
@Entity
@Table(name = "TICKETS")
public class Ticket {

  /**
   * The unique identifier for this ticket.
   * Automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The duration associated with this ticket.
   * Cannot be null.
   */
  @Column(nullable = false)
  private Date duration;

  /**
   * The price of the ticket.
   * Cannot be null.
   */
  @Column(nullable = false)
  private int price;
}
