package com.example.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.sql.Date;

/**
 * Represents a trip made using a specific vehicle along a specific route.
 *
 * <p>Each trip has a start and end date, is associated with one vehicle,
 * and follows one route.
 * </p>
 *
 * <p>This entity is mapped to the {@code TRIPS} table in the database.
 * </p>
 */
@Entity
@Table(name = "TRIPS")
public class Trip {

  /**
   * Unique identifier of the trip.
   *
   * <p>This value is automatically generated by the database.
   * </p>
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * The date when the trip starts.
   *
   * <p>Cannot be null.
   * </p>
   */
  @Column(nullable = false)
  private Date startDate;

  /**
   * The date when the trip ends.
   *
   * <p>Cannot be null.
   * </p>
   */
  @Column(nullable = false)
  private Date endDate;

  /**
   * The vehicle used for this trip.
   *
   * <p>Represents a many-to-one relationship to the {@link Vehicle} entity.
   * Cannot be null.
   * </p>
   */
  @ManyToOne(optional = false)
  @JoinColumn(name = "VEHICLE_ID", nullable = false,
      foreignKey = @ForeignKey(name = "FK_TRIP_VEHICLE"))
  private Vehicle vehicle;

  /**
   * The route followed during this trip.
   *
   * <p>Represents a many-to-one relationship to the {@link Route} entity.
   * Cannot be null.
   * </p>
   */
  @ManyToOne(optional = false)
  @JoinColumn(name = "ROUTE_ID", nullable = false,
      foreignKey = @ForeignKey(name = "FK_TRIP_ROUTE"))
  private Route route;

}
